# Generated by Django 4.2.2 on 2023-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ankieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.PositiveSmallIntegerField()),
                ('wzrost', models.PositiveSmallIntegerField()),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('kolor', models.CharField(choices=[('Z', 'Zielony'), ('N', 'Niebieski'), ('C', 'Czerwony')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ankiety',
                'ordering': ['created_at'],
            },
        ),
    ]
