# Generated by Django 4.2.2 on 2023-06-27 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankieta',
            name='wiek',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='ankieta',
            name='wzrost',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
